platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/qp-gpdbdev
inputs:
  - name: bin_orca
  - name: bin_xerces
  - name: gpdb_tarball
  - name: gpdb
outputs:
  - name: bin_gpdb
  - name: package_tarball
run:
  path: gpdb/concourse/scripts/untar_and_build_gpdb.py
