## ======================================================================
## Pipeline for GPDB s3ext
## ======================================================================

resources:
- name: gpdb_src
  type: git
  source:
    branch: 4.3_STABLE
    private_key: {{private-repo-key}}
    uri: git@github.com:greenplum-db/gpdb4.git
- name: centos6-gpdb-image
  type: docker-image
  source:
    repository: gpdbunitedockers/centos6-gcc48-gpdb-s3
    username: {{docker_username_centos6}}
    password: {{docker_password_centos6}}
    email: hawang@pivotal.io
- name: centos5-gpdb-image
  type: docker-image
  source:
    repository: gpdbunitedockers2/centos511-gcc442-s3
    username: {{docker_username_centos5}}
    password: {{docker_password_centos5}}
    email: pqiu@pivotal.io
jobs:
- name: compile_s3_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      trigger: true
      params: {submodules: none}
    - get: centos5-gpdb-image
  - task: build_gpdb
    file: gpdb_src/ci/concourse/compile_s3.yml
    image: centos5-gpdb-image

- name: unit_tests_s3_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      trigger: true
      passed: [compile_s3_centos]
      params: {submodules: none}
    - get: centos6-gpdb-image
  - task: unit_test_s3
    file: gpdb_src/ci/concourse/unittest_s3.yml
    image: centos6-gpdb-image

- name: regression_tests_s3_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      passed: [compile_s3_centos]
      trigger: true
      params: {submodules: none}
    - get: centos5-gpdb-image
  - task: regression_test_s3
    file: gpdb_src/ci/concourse/regression_test_s3.yml
    image: centos5-gpdb-image
    params:
      s3conf: {{s3_conf_key}}

- name: gpcheckcloud_tests_s3_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      passed: [compile_s3_centos]
      trigger: true
      params: {submodules: none}
    - get: centos5-gpdb-image
  - task: regression_test_s3
    file: gpdb_src/ci/concourse/gpcheckcloud_test_s3.yml
    image: centos5-gpdb-image
    params:
      s3conf: {{s3_conf_key}}

- name: stage_s3_centos
  public: true
  plan:
  - aggregate:
    - get: gpdb_src
      trigger: true
      params: {submodules: none}
      passed:
            - unit_tests_s3_centos
            - regression_tests_s3_centos
            - gpcheckcloud_tests_s3_centos
    - get: centos5-gpdb-image
  - task: staging_s3
    file: gpdb_src/ci/concourse/stage_s3.yml
    image: centos5-gpdb-image
    params:
      EC2_PRIVATE_KEY: {{ec2_key}}
      EC2_INSTANCE_IP: {{ec2_ip}}
